# Install dependencies only when needed
FROM node:18 AS deps
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

RUN echo ${HOSTNAME}
# Rebuild the source code only when needed
FROM node:18 AS runner

ENV NEXT_TELEMETRY_DISABLED 1
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

CMD npm run dev
