ARG POSITIONSTACK_API_KEY

# Install dependencies only when needed
FROM node:16 AS deps
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM node:16 AS runner

ARG POSITIONSTACK_API_KEY
ENV POSITIONSTACK_API_KEY ${POSITIONSTACK_API_KEY}


ENV NEXT_TELEMETRY_DISABLED 1
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

CMD npm run dev
